# Generated by Django 6.0.2 on 2026-02-21 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('deadline', models.DateField()),
                ('complexity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effort_hours', models.FloatField(blank=True, null=True)),
                ('capacity_hours', models.FloatField(blank=True, null=True)),
                ('days_needed', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_finish_date', models.DateField(blank=True, null=True)),
                ('red_zone', models.BooleanField(default=False)),
                ('red_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('DEVOPS', 'DevOps')], max_length=10)),
                ('seniority', models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devs', to='app.project')),
            ],
        ),
    ]
